### ISSUE TITLE
Issue: Differing chart contents?

### ISSUE THREAD

**Issue by BrianPark314** [vllm-project/production-stack#102]
### Describe the issue
The helm repo provided in the blog https://lmcache.github.io/helm/vllm-stack is not working. Hence, I am using this url https://vllm-project.github.io/production-stack to run `helm dependency build` to deploy vllm-stack as a subchart. However I've noticed differing contents in the github repo and the actual chart deployed. In the `deployment-router.yaml` template, 
router resources are hard-coded as following:
```yaml
        resources: # TODO: update here
          requests:
            cpu: "4"
            memory: "16G"
        ports:
          - name: "router-cport"
            containerPort: {{ .Values.routerSpec.containerPort }}
```

yet in the main branch of the `production-stack` repo, resource override is correctly implemented.

```yaml
        resources:
          {{- if .Values.routerSpec.resources.requests }}
          requests:
            cpu: "{{ .Values.routerSpec.resources.requests.cpu }}"
            memory: "{{ .Values.routerSpec.resources.requests.memory }}"
          {{- end }}
          {{- if .Values.routerSpec.resources.limits }}
          limits:
            cpu: "{{ .Values.routerSpec.resources.limits.cpu }}"
            memory: "{{ .Values.routerSpec.resources.limits.memory }}"
          {{- end }}
        {{- end }}
```
