### ISSUE TITLE
bug: PVC accessMode fixed to ReadWriteOnce, preventing more than one pod from accessing it.

### ISSUE THREAD

**Issue by BrianPark314** [vllm-project/production-stack#107]
### Describe the bug

```yaml
{{- range $modelSpec := .Values.servingEngineSpec.modelSpec }}
{{- with $ -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-{{$modelSpec.name}}-storage-claim"
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $modelSpec.pvcStorage }}
  {{- if not (empty $modelSpec.pvcMatchLabels) }}
  selector:
    matchLabels:
      {{- toYaml $modelSpec.pvcMatchLabels | nindent 8 }}
  {{- end }}
{{- end }}
---
{{- end }}

```
As stated in the title, PVC settings are:
1. Blocking rolling update
2. breaking multi-pod deployment of the serveEngine

### To Reproduce

Set replicaset: 2 or larger for serveEngine
