### ISSUE TITLE
The tutorials all suggest storing your tokens as plaintext

### ISSUE THREAD

**Issue by joerunde** [vllm-project/production-stack#14]
Just a heads up that all of your tutorials suggest setting your HF token in plaintext as an environment variable in the deployments like
```
    env:
      - name: HF_TOKEN
        value: <YOUR_HF_TOKEN>
```

This _might_ be fine to do on a local minikube cluster on your machine, but it's super unsafe to do on a remote cluster.

I'd suggest setting up a secret in the helm chart to hold the token, so that it can be safely referenced in the deployment instead like:
```
    env
       - name: HF_TOKEN
         valueFrom:
           secretKeyRef:
             name: hf-token-secret
             key: token
```
