### ISSUE TITLE
bug: startupProbe wasn't respected

### ISSUE THREAD

**Issue by garyfanhku** [vllm-project/production-stack#220]
### Describe the bug

This is the helm values
```
sudo helm get values vllm -n default | grep startupProbe -A 10
    startupProbe:
      failureThreshold: 120
      initialDelaySeconds: 900
      periodSeconds: 30
    tag: v0.7.3
    vllmConfig:
      extraArgs:
      - --disable-log-requests
      - --gpu-memory-utilization
      - "0.80"
      - --enable-auto-tool-choice
--
    startupProbe:
      failureThreshold: 120
      initialDelaySeconds: 900
      periodSeconds: 30
    tag: v0.7.3
    vllmConfig:
      extraArgs:
      - --disable-log-requests
      - --gpu-memory-utilization
      - "0.80"
      - --enable-auto-tool-choice
 ```

And this is the pod spec:

```
startupProbe:
      failureThreshold: 60
      httpGet:
        path: /health
        port: 8000
        scheme: HTTP
      initialDelaySeconds: 15
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    terminationMessagePath: /dev/termination-log
```

Helm values are bypassed in the actual pod specification, resulting in pod restart

### To Reproduce

sudo helm install vllm vllm/vllm-stack -f tutorials/assets/values-04-multiple-models.yaml

**Comment by AbelHristodor** [comment]
Hi, I've just tried modifying `helm/values-example.yaml` with your config e.g.
```yaml
servingEngineSpec:
  modelSpec:
    - name: "opt125m"
      repository: "lmcache/vllm-openai"
      tag: "latest"
      modelURL: "facebook/opt-125m"

      replicaCount: 1

      requestCPU: 6
      requestMemory: "16Gi"
      requestGPU: 1

      pvcStorage: "10Gi"

  startupProbe:
    failureThreshold: 120
    initialDelaySeconds: 900
    periodSeconds: 30
  tag: v0.7.3
  vllmConfig:
    extraArgs:
      - --disable-log-requests
      - --gpu-memory-utilization
      - "0.80"
      - --enable-auto-tool-choice
```

and then run `helm template -f values-example.yaml .` and the output is correct:
```yaml
<deployment conf>
          startupProbe:
            failureThreshold: 120
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 900
            periodSeconds: 30
```

Try **double-checking** that the indentation on your yaml file is correct.

Also **note that** `vllmConfig` is not indented correctly, it must be at the same indent-level as `pvcStorage`, check the correct yaml below:
```yaml
servingEngineSpec:
  modelSpec:
    - name: "opt125m"
      repository: "lmcache/vllm-openai"
      tag: v0.7.3
      modelURL: "facebook/opt-125m"

      replicaCount: 1

      requestCPU: 6
      requestMemory: "16Gi"
      requestGPU: 1

      pvcStorage: "10Gi"
      vllmConfig:
        extraArgs:
          - --disable-log-requests
          - --gpu-memory-utilization
          - "0.80"
          - --enable-auto-tool-choice
  startupProbe:
    failureThreshold: 120
    initialDelaySeconds: 900
    periodSeconds: 30
```
