### ISSUE TITLE
The output got stuck when I configured lmcacheConfig in yaml

### ISSUE THREAD

**Issue by Cangxihui** [vllm-project/production-stack#292]
When I configured lmcacheConfig, the output got stuck here ，I wonder if there is some mistakes in my my-config.yaml configuration file?   
I used 4 * Tesla v100 for this try.
The process refers to https://github.com/vllm-project/production-stack/blob/main/tutorials/05-offload-kv-cache.md

Here is the content of my my-config.yaml 
```
**my-config.yaml** 
servingEngineSpec:
  runtimeClassName: ""
  modelSpec:
  - name: "deepseek"
    repository: "lmcache/vllm-openai"   
    tag: "2025-03-10"
    modelURL: "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B"   

    replicaCount: 1
    requestCPU: 6
    requestMemory: "60Gi"      
    requestGPU: 4

    pvcStorage: "20Gi"         # At least The amount of storage requested for the model  
    pvcAccessMode:
      - ReadWriteOnce           # due to "replicaCount: 1"

    vllmConfig:
      enableChunkedPrefill: true
      enablePrefixCaching: true
      maxModelLen: 3200
      extraArgs: ["--disable-log-requests", "--dtype","half","--tensor-parallel-size","4"]
    
    
    lmcacheConfig: 
      enabled: true
      cpuOffloadingBufferSize: "20"

    shmSize: "10Gi"

```

**This is the log I tried this time**
![Image](https://github.com/user-attachments/assets/ff035e2b-891d-4bb1-864f-b88f78344ddb)

How can i deal with this problem? Thanks in advance
