### ISSUE TITLE
Question-Is there any solution to load a local model?

### ISSUE THREAD

**Issue by Cangxihui** [vllm-project/production-stack#304]
Is any reference or method to load a local model with vLLM Production Stack?
I have tried some methods, but it seems that it cannot access my local model path.
Can anyone provide some suggestions on which configurations I should modify? I would really appreciate it!

**Comment by Shaoting-Feng** [comment]
Does [this tutorial](https://github.com/vllm-project/production-stack/blob/main/tutorials/03-load-model-from-pv.md) meet your needs? You first load model into the Persistent Volume and then link the PV to your application.

**Comment by Cangxihui** [comment]
Thank you for your suggestion!
Before asking this question, I had already referred to the tutorial you mentioned. However, it seems that it cannot access the model I downloaded. I received the following error message:

```
ValueError: Invalid repository ID or local directory specified: '/root/deepseek-ai/DeepSeek-R1-Distill-Qwen-7B'.

Please verify the following requirements:

Provide a valid Hugging Face repository ID.
Specify a local directory that contains a recognized configuration file.
For Hugging Face models: ensure the presence of a 'config.json' file.
For Mistral models: ensure the presence of a 'params.json' file.

```

My model is downloaded to this path: /root/deepseek-ai/DeepSeek-R1-Distill-Qwen-7B.
And pv.yaml  ：
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-vllm-pv
  labels:
    model: "deepseek-pv"
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /root/deepseek-ai

```


In my-config.yaml， I don't know how to set the modelURL parameter to access the model I downloaded.
Setting modelURL to "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B" does not throw an error, but it seems like it is not loading the model I previously downloaded. If I set it to anything else, it results in an error.



```

servingEngineSpec:
  runtimeClassName: ""
  modelSpec:
  - name: "deepseek"
    repository: "vllm/vllm-openai"   
    tag: "latest"
    modelURL: "/root/deepseek-ai/DeepSeek-R1-Distill-Qwen-7B"   

    replicaCount: 1
    requestCPU: 6
    requestMemory: "30Gi"      
    requestGPU: 4

    pvcStorage: "20Gi"      
    pvcMatchLabels:
      model: "deepseek-pv"

    vllmConfig:
      enableChunkedPrefill: true
      enablePrefixCaching: true
      maxModelLen: 3200
      extraArgs: ["--disable-log-requests", "--dtype","half","--tensor-parallel-size","4"]
    
    
    lmcacheConfig: 
      enabled: true
      cpuOffloadingBufferSize: "20"

    shmSize: "10Gi"

```

**Comment by Shaoting-Feng** [comment]
I suggest setting the modelURL to "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B" and downloading the model into your hosted persistent volume the first time, instead of having the model already downloaded. Then, follow the tutorial (`run kubectl delete -f tutorials/assets/pv-03.yaml && kubectl apply -f tutorials/assets/pv-03.yaml`) to observe a faster startup.

**Comment by Cangxihui** [comment]
Thank you for your advice! I want to do some benchmarking on the DeepSeek-R1 617B model, so I plan to download the model first and then directly load the locally downloaded model. If I set the modelURL to "deepseek-ai/DeepSeek-R1", I feel there might be issues with downloading because the model is too large.

**Comment by Shaoting-Feng** [comment]
I think that as long as the files and naming conventions in /root/deepseek-ai conform to Hugging Face’s requirements, using a local model should work fine.

**Comment by Cangxihui** [comment]
I used this command to download the model:
`huggingface-cli download deepseek-ai/DeepSeek-R1-Distill-Qwen-7B --local-dir ./deepseek-ai/DeepSeek-R1-Distill-Qwen-7B --resume-download`

**Comment by JustinDuy** [comment]
I would try to run vllm serve locally with that path first. I used Qwen-7B-Instruct on a k8s persistent volume with the model path like this "/mnt/cache/hf_models/Qwen2-VL-7B-Instruct" and set env variable HF_HUB_OFFLINE=1. You probably want to check if there is a config.json inside the model path.

<img width="599" alt="Image" src="https://github.com/user-attachments/assets/47903fc3-9479-45d0-ae59-0a076a076816" />

**Comment by JGillette71** [comment]
The tutorial steps nor adding `HF_HUB_OFFLINE` seemed to help with this. I can successfully load the model files into the servicing engine file system at `/data/all-roberta-large-v1' and set `servingEngineSpec.modelSpec.modelURL` to the same path, but no bueno. 

`curl -v http://vllm-router-service.vllm-ns.svc.cluster.local/v1/models | jq` is still returning an empty array.

```json
{
  "object": "list",
  "data": []
}
```

`curl -v http://vllm-router-service.vllm-ns.svc.cluster.local/health` still returns `{"status":"healthy"}`.

This is a snippet from the custom values.yaml for the model engine.

```yaml
servingEngineSpec:
  runtimeClassName: "" # Overwrite RuntimeClass set to "nvidia" prompting CPU usage
  enableEngine: true
  modelSpec:
    - name: "all-roberta-large-v1"
      repository: "public.ecr.aws/q9t5s3a7/vllm-cpu-release-repo"
      tag: "v0.7.2"
      modelURL: "/data/all-roberta-large-v1"  
      # Required top-level fields
      requestCPU: "1"         
      requestMemory: "2Gi"    
      resources:
        requests:
          cpu: "1"
          memory: "2Gi"
        limits:
          cpu: "2"
          memory: "4Gi"
      extraArgs: ["--task", "embed"]
      env:
        - name: HF_HUB_OFFLINE
          value: "1"
      pvcStorage: "3Gi"
      initContainer:
        name: "model-fetch"
        image: "minio/mc:latest"    # using latest tag for the ARM64 image
        command: ["sh", "-c"]
        args:
          - |
            echo "Starting alias command" && \
            sleep 10 && \
            mc alias set minio --insecure http://minio.minio-ns.svc.cluster.local:9900 <MINIO_USER> <MINIO_PASS> && \
            mkdir -p /data  && \
            mc mirror minio/updf-dev/models/sentence-transformers/all-roberta-large-v1 /data/all-roberta-large-v1
        mountPvcStorage: true
        volumeMounts:
          pvcStorage:
            name: model-cache
            mountPath: "/data"
```

Not sure what I'm missing...
