### ISSUE TITLE
bug: vLLM pod crashes if remote shared storage takes time to bootstrap

### ISSUE THREAD

**Issue by Stephen-X** [vllm-project/production-stack#310]
### Describe the bug

This is in regard to adding LMCache as remote shared storage: https://github.com/vllm-project/production-stack/pull/188.

In practice, the remote cache server can take time to bootstrap, which can crash vLLM in the inference pods because they expect remote storage to be up and running first as per: https://github.com/LMCache/LMCache/blob/b9668e38ba003e6206e0dc853a4868d14347d7e9/examples/storage_backends/README.md

Unfortunately inference pods' health check doesn't cause them to be restarted either (should I file a separate bug for this?), so all pods remain running but they can't process any inference requests.

### To Reproduce

It appears scheduling the remote shared storage pod on the agent pool (which doesn't have GPUs) is enough to reproduce the bug reliably for me; it takes significantly longer time to bootstrap the `lmcache/vllm-openai` container on CPUs.

### Additional context

A way to fix this would be to add an `initContainer` to the inference pods that runs a simple script looping a `sleep` command until the remote cache server health probe returns 200. Example: https://stackoverflow.com/questions/51079849/kubernetes-wait-for-other-pod-to-be-ready

But right now the remote cache server doesn't appear to have an health probe to begin with: https://github.com/vllm-project/production-stack/blob/82b47eb43322a26de9ce46309dadf25134b67de9/helm/templates/deployment-cache-server.yaml#L44

Another way would be to make two helm charts instead, and let the remote cache server chart be a [helm dependency](https://helm.sh/docs/helm/helm_dependency/) of the inference chart.

**Comment by YuhanLiu11** [comment]
thanks for submitting the issue. 
@YaoJiayi Can you take a look at this issue?

**Comment by YuhanLiu11** [comment]
Hey @Stephen-X Would you mind sharing the helm chart values yaml to help us reproduce? 
BTW I recently tested this PR and I can run it following the [example yaml file](https://github.com/vllm-project/production-stack/blob/main/tutorials/06-remote-shared-kv-cache.md#step-1-configuring-kv-cache-shared-storage) in the [tutorial](https://github.com/vllm-project/production-stack/blob/main/tutorials/06-remote-shared-kv-cache.md)

**Comment by Stephen-X** [comment]
> Hey [@Stephen-X](https://github.com/Stephen-X) Would you mind sharing the helm chart values yaml to help us reproduce? BTW I recently tested this PR and I can successfully run it following the [example yaml file](https://github.com/vllm-project/production-stack/blob/main/tutorials/06-remote-shared-kv-cache.md#step-1-configuring-kv-cache-shared-storage) in the [tutorial](https://github.com/vllm-project/production-stack/blob/main/tutorials/06-remote-shared-kv-cache.md).

Hi @YuhanLiu11, thank you for following up. I was able to reproduce with the tutorial you mentioned above and the [Standard_D4ds_v5](https://instances.vantage.sh/azure/vm/d4ds-v5) node pools for the LMCache cache server.

I don't think you need to specifically repro this bug though, the root cause is **there's no deployment order guarantee in the current solution where the LMCache remote server would finish bootstraping first before the vLLM pods**. vLLM specifically requires that the KV transfer server to be up and running first, as also noted in the [LMCache doc](https://github.com/LMCache/LMCache/blob/b9668e38ba003e6206e0dc853a4868d14347d7e9/examples/storage_backends/README.md#remote-backend):

```
Remember to start remote server before starting vllm.
```

Because there's no standard way to guarantee pod deployment order within the same deployment, the standard practice is to (1) implement health probes in the remote cache server (the TODO item I linked in the main post), then (2) add an init container to the vLLM pods that probes the endpoint.

An example:

```yaml
      initContainers:
        - name: wait-for-cache-server
          image: busybox
          command:
            - /bin/sh
          args:
            - -c
            - |
              while ! nc -z {{ include "cacheServer.formatRemoteUrl" (dict "service_name" (print .Release.Name "-cache-server-service") "port" $engineSpec.lmCacheConfig.externalServer.servicePort) }}; do
                echo Waiting for remote cache server to finish bootstrapping...
                sleep 2
              done
```
