### ISSUE TITLE
bug: Multiple engines with different models sharing same service instance.

### ISSUE THREAD

**Issue by dumb0002** [vllm-project/production-stack#312]
### Describe the bug

When launching multiple models in vLLM Production Stack, the deployed engines share the same single service instance even when configured with different models. 

For example: I used production stack to launch two engines with the following models: `facebook/opt-125m` and `openai-community/gpt2`. It generates a single service listening to a single port: 

```
$kubectl  get svc vllm-engine-service -o yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: vllm
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
    environment: test
    release: test
  name: vllm-engine-service
  namespace: default
spec:
  clusterIP: 172.21.14.236
  clusterIPs:
  - 172.21.14.236
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: service-port
    port: 80
    protocol: TCP
    targetPort: container-port
  selector:
    environment: test
    release: test
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

Furthermore: this service is associated with both pods. 

```
$kubectl get endpoints
NAME                                                   ENDPOINTS                                    AGE
vllm-engine-service           172.30.116.172:8000,172.30.189.180:8000   12m
```

### To Reproduce

Use production-stack to launching multiple models, for example:

```
servingEngineSpec:
  runtimeClassName: ""
  labels:
     environment: "test"
     release: "test"
  modelSpec:
  - name: "opt125m"
    repository: "vllm/vllm-openai"
    tag: "latest"
    modelURL: "facebook/opt-125m"
    pvcStorage: "10Gi"
    replicaCount: 1
    requestCPU: 6
    requestMemory: "16Gi"
    requestGPU: 1
  - name: "gpt2"
    repository: "vllm/vllm-openai"
    tag: "latest"
    modelURL: "openai-community/gpt2"
    pvcStorage: "10Gi"
    replicaCount: 1
    requestCPU: 6
    requestMemory: "16Gi"
    requestGPU: 1
```

### Expected behavior

Each engine should be associated with a unique service instance.
