### ISSUE TITLE
Fix Installation Steps in vLLM Production Stack Tutorials

### ISSUE THREAD

**Issue by dxu104** [vllm-project/production-stack#37]
#### **Issue Description:**
I tried to reproduce the tutorials:  

- [[01-minimal-helm-installation](https://github.com/vllm-project/production-stack/blob/main/tutorials/01-minimal-helm-installation.md)](https://github.com/vllm-project/production-stack/blob/main/tutorials/01-minimal-helm-installation.md)  
- [[02-basic-vllm-config](https://github.com/vllm-project/production-stack/blob/main/tutorials/02-basic-vllm-config.md)](https://github.com/vllm-project/production-stack/blob/main/tutorials/02-basic-vllm-config.md)  

However, I encountered the following issues:

1. **Helm Chart Name Issue:**  
   The command in the tutorial:
   ```sh
   helm install vllm vllm/production-stack -f tutorials/assets/values-02-basic-config.yaml
   ```
   results in an error:  
   ```
   Error: INSTALLATION FAILED: chart "production-stack" matching not found in vllm index. (try 'helm repo update'): no chart name found
   ```
   **Fix:** Change the command to:  
   ```sh
   helm install vllm vllm/vllm-stack -f tutorials/assets/values-02-basic-config.yaml
   ```

2. **Persistent Volume (PV) Requirement:**  
   Before running `helm install`, we need to create a Persistent Volume (PV), or the Pod will be stuck in `Pending` state with the error:
   ```
   0/1 nodes are available: pod has unbound immediate PersistentVolumeClaims.
   ```
   **Fix:** Apply `pv.yaml` first:
   ```sh
   kubectl apply -f pv.yaml
   ```
   **pv.yaml:**
   ```yaml
   apiVersion: v1
   kind: PersistentVolume
   metadata:
     name: vllm-pv
   spec:
     capacity:
       storage: 50Gi
     accessModes:
       - ReadWriteOnce
     persistentVolumeReclaimPolicy: Retain
     hostPath:
       path: "/mnt/data/vllm"
   ```

3. **Model Access Permissions on Hugging Face:**  
   Some models require users to **log in to Hugging Face and request access** before they can be used. Without proper access, the model download will fail.

Would be great to update the tutorial to include these steps to help users avoid common issues! 🚀
