### ISSUE TITLE
feature: Perform functionality tests for Helm charts without relying on external virtual machines (VMs) using GitHub's built-in features

### ISSUE THREAD

**Issue by haitwang-cloud** [vllm-project/production-stack#387]
### Updated Workflow Example

```yaml
name: Functionality test for helm chart
run-name: ${{ github.actor }} is testing Helm chart functions 🚀

on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - 'helm/**'
  pull_request:
    paths:
      - '.github/**'
      - 'helm/**'

jobs:
  functionality-test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository code
      - name: Check out repository code
        uses: actions/checkout@v4

      # Step 2: Set up Kubernetes using Kind
      - name: Set up Kind (Kubernetes in Docker)
        uses: helm/kind-action@v1.4.0
        with:
          version: v1.27.3

      # Step 3: Build Docker image for Helm chart deployment and load it into Kind
      - name: Build Docker image and load into Kind
        run: |
          docker build --build-arg INSTALL_OPTIONAL_DEP=default -t localhost:5000/git-act-router -f docker/Dockerfile .
          kind load docker-image localhost:5000/git-act-router

      # Step 4: Deploy Helm chart
      - name: Deploy Helm Chart
        run: |
          helm install vllm ./helm -f .github/values-05-secure-vllm.yaml

      # Step 5: Validate the installation
      - name: Validate the installation and send queries
        run: |
          bash .github/port-forward.sh curl-05-secure-vllm
        timeout-minutes: 2

      # Step 6: Archive test results
      - name: Archive test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: output-05-secure-vllm
          path: |
            output-05-secure-vllm/

      # Step 7: Clean up resources
      - name: Uninstall Helm Chart and clean up
        run: |
          helm uninstall vllm
        if: always()
```

---

### Key Adjustments Made

1. **Replaced `self-hosted` with `ubuntu-latest`:**
   - GitHub's hosted runners (`ubuntu-latest`) are used to avoid reliance on external VMs.

2. **Added Kubernetes Environment with Kind:**
   - Using the `helm/kind-action` GitHub Action, a local Kubernetes cluster is created in Docker for testing Helm charts.

3. **Docker Image Built and Loaded into Kind:**
   - The Docker image required for the Helm chart is built and loaded directly into the Kind cluster.

4. **Helm Chart Deployed and Tested Locally:**
   - The Helm chart is installed into the Kind cluster and validated by running specific test commands.

5. **Resource Cleanup:**
   - The Helm release is uninstalled after tests to ensure a clean environment.

---

### Benefits of This Approach
- **No External VM Dependency:** Everything runs within GitHub Actions, eliminating the need for external resources.
- **Local Kubernetes Cluster:** Kind enables a lightweight Kubernetes setup for testing Helm charts.
- **Cost-Efficient:** GitHub-hosted runners are used without additional infrastructure.
- **Fully Automated:** The workflow is self-contained and reusable for CI/CD.

You can extend this workflow to include additional tests or configurations as needed. Let me know if you need further assistance!
