### ISSUE TITLE
feature: add model aliases

### ISSUE THREAD

**Issue by max-wittig** [vllm-project/production-stack#389]
Previously we used [litellm](https://github.com/BerriAI/litellm) and there we could define model aliases.

See the [documentation in litellm](https://docs.litellm.ai/docs/completion/model_alias)

This can be used, for example to map known commercial model names to local ones or route older models to newer more performant ones to preserve compatibility in existing configurations of end users.

E.g. this was our configuration so when a user requested `gpt-4`, the request would just be served by `mistral-7b-instruct` in the background.

```yaml
router_settings:
  model_group_alias:
    gpt-4: mistral-7b-instruct
    gpt-3.5-turbo: mistral-7b-instruct
    gpt-3.5-turbo-16k: mistral-7b-instruct
    gpt-4-32k: mistral-7b-instruct
    codellama-13b-instruct: mistral-7b-instruct
    text-embedding-3-small: bge-m3
    text-embedding-3-large: bge-m3
```

In addition it was possible to hide these aliases in the `v1/models` models endpoint.

I think that would be a great addition. Thanks for your consideration!

### Why do you need this feature?

* preserve compatibility of model names when newer models are released
* allow users to specify known commercial models and route the requests to open weight models instead

/cc @nejch
