### ISSUE TITLE
feature: 🛡️ Integrate Checkov for Static security Analysis via Pre-Commit Hooks

### ISSUE THREAD

**Issue by brokedba** [vllm-project/production-stack#462]
### Describe the feature

Hi team , Cc  @hickeyma

As mentioned in today's meeting, I’d like to suggest exploring [Checkov](https://www.checkov.io/) to enhance static code analysis as part of our pre-commit workflow.

### Why do you need this feature?
Helps shift security left with minimal friction

**Why it matters:**

- Supports 35+ frameworks (Helm, K8s, docker, YAML, python, go, github etc.)
- Detects misconfigurations, insecure defaults, and best practice violations
- Can be configured to warn on non-blocking issues or fail on critical ones 

### Additional context

**Proposed usage:**

- Add checkov to the `.pre-commit-config.yaml`
- Set up basic policy thresholds (e.g., allow WARN, block HIGH/CRITICAL)
-  Can implement soft-fail mode at the very beginning 
- Auto-scan  code, helm, k8s manifests before PRs are merged can target specific sub directory to reduce overhead

Here is an example I did around terraform for a hashiCorp webinar a while ago .

https://github.com/brokedba/checkov_demo/tree/main?tab=readme-ov-file#i-pre-commit-locally

```
.pre-commit-config.yaml
--- 
vi `.pre-commit-config.yaml`
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.89.1 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_checkov
      args:
        - --args=--quiet
        - --args=--skip-check CKV2_AWS_8
        - --args=--check CKV_AWS_186
        - --args=--framework terraform  <------- choose appropriate framework
        - --args=--compact
        - --args=--file code/deployment_ec2.tf  <---- choose file or wildcard based expression or Sub-directory
```

Let me know if you want to a pre-commit  hook source repo if you have a framework in mind (can ask a friend at Palo alto networks)
**List of frameworks :** 
```
ansible, argo_workflows, arm, azure_pipelines, bicep, bitbucket_pipelines, cdk, circleci_pipelines, cloudformation, 
dockerfile, github_configuration, github_actions, gitlab_configuration, gitlab_ci, bitbucket_configuration, helm, 
json, yaml, kubernetes, kustomize, openapi, sca_package, sca_image, secrets, serverless, terraform, terraform_json, 
terraform_plan, sast, sast_python, sast_java, sast_javascript, sast_typescript, sast_golang, 3d_policy
```
Cheers 
Kosseila
