### ISSUE TITLE
bug: ray cluster helm chart error

### ISSUE THREAD

**Issue by JustinDuy** [vllm-project/production-stack#507]
### Describe the bug

While deploying vllm-stack with pipeline parallelism, i encountered this error in the configmap env reference: 
<img width="1256" alt="Image" src="https://github.com/user-attachments/assets/94546c57-6504-4c3c-9e52-204224c90030" />. Looking into to [ray-cluster.yaml,](https://github.com/vllm-project/production-stack/blob/main/helm/templates/ray-cluster.yaml#L370) i think envFrom block is located outside of env. Can you please confirm this @ahinsutime, @YuhanLiu11 

### To Reproduce

deploy with raySpec:
```
servingEngineSpec:
  # runtimeClassName: ""
  enableEngine: true
  labels:
    sidecar.istio.io/inject: "false"
  vllmApiKey: 
    secretName: "vllm-api-key"
    secretKey: "VLLM_API_KEY"
  modelSpec:
    - name: "deepcoder-14b-preview"
      repository: "vllm/vllm-openai"
      tag: "v0.7.2"
      modelURL: "/data/DeepCoder-14B-Preview"  
      replicaCount: 1

      requestCPU: 78
      requestMemory: "284Gi"
      requestGPU: 4

      limitCPU: 84
      limitMemory: "300Gi"
      limitGPU: 4

      shmSize: "128Gi"

      storageClass: "fsx-ontap-silver"
      pvcStorage: "512Gi"
      pvcAccessMode:
      - ReadWriteMany


      vllmConfig:
        maxModelLen: 131072
        tensorParallelSize: 4
        pipelineParallelSize: 2
        enableChunkedPrefill: true
        enablePrefixCaching: true
        v1: 1
        extraArgs: ["--gpu-memory-utilization", "0.95"]

      raySpec:
        headNode:
          requestCPU: 78
          requestMemory: "248Gi"
          requestGPU: 4
      hf_token: ""
      env:
        - name: HF_HUB_OFFLINE
          value: "1"
      initContainer:
        name: "model-fetch"
        image: "xxx/llm/huggingface-download"
        args:
          - --model-url
          - "agentica-org/DeepCoder-14B-Preview"
          - --local-dir
          - "/data/DeepCoder-14B-Preview"
        env:
        - name: HF_HUB_ETAG_TIMEOUT
          value: "86400"
        - name: HF_HUB_DOWNLOAD_TIMEOUT
          value: "86400"
        - name: HF_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: hf
              key: HF_ENDPOINT
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf
              key: HF_TOKEN
        mountPvcStorage: true
        volumeMounts:
          pvcStorage:
            name: deepcoder-14b-preview-deepcoder-14b-preview-storage-claim
            mountPath: "/data"

  nodeSelectorTerms:
  - matchExpressions:
    - key: instance-type
      operator: "In"
      values:
      - "g5.24xlarge"
  tolerations:
  - key: "as_gpu_g5_24xlarge_ns"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  - key: "as_gpu_g5_24xlarge_ne"
    operator: "Equal"
    value: "true"
    effect: "NoExecute"

routerSpec:
  repository: "lmcache/lmstack-router"
  tag: "0.1.4.dev8-g7b5a59f"
  labels:
    environment: "router"
    release: "router"
    sidecar.istio.io/inject: "false"
  resources:
    requests:
      cpu: "2"
      memory: "4Gi"
    limits:
      cpu: "2"
      memory: "4Gi"
```
`
helm install vllm value.yaml  --debug`

### Additional context
Here is the debug error:
```
Error: INSTALLATION FAILED: YAML parse error on vllm-stack/templates/ray-cluster.yaml: error converting YAML to JSON: yaml: line 141: did not find expected key
helm.go:84: [debug] error converting YAML to JSON: yaml: line 141: did not find expected key
YAML parse error on vllm-stack/templates/ray-cluster.yaml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
	helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:146
helm.sh/helm/v3/pkg/releaseutil.SortManifests
	helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:106
helm.sh/helm/v3/pkg/action.(*Configuration).renderResources
	helm.sh/helm/v3/pkg/action/action.go:168
helm.sh/helm/v3/pkg/action.(*Install).RunWithContext
	helm.sh/helm/v3/pkg/action/install.go:312
main.runInstall
	helm.sh/helm/v3/cmd/helm/install.go:314
main.newInstallCmd.func2
	helm.sh/helm/v3/cmd/helm/install.go:156
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.8.0/command.go:983
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.8.0/command.go:1115
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.8.0/command.go:1039
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
	runtime/proc.go:271
runtime.goexit
	runtime/asm_arm64.s:1222
INSTALLATION FAILED
main.newInstallCmd.func2
	helm.sh/helm/v3/cmd/helm/install.go:158
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.8.0/command.go:983
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.8.0/command.go:1115
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.8.0/command.go:1039
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
	runtime/proc.go:271
runtime.goexit
	runtime/asm_arm64.s:1222
```

_No response_
