### ISSUE TITLE
bug: doube security context in deployment-vllm-multi.yaml

### ISSUE THREAD

**Issue by VonNao** [vllm-project/production-stack#543]
### Describe the bug

We tried to deploy the production stack with argocd but getting the following error 

```
failed exit status 1: Error: map[string]interface {}(nil): yaml: unmarshal errors: line 55: mapping key "securityContext" already defined at line 38
```
values.yaml
```
servingEngineSpec:
  enableEngine: true
  runtimeClassName: "nvidia"
  vllmApiKey: "testkey"
  labels:
    release: "2025"
  containerSecurityContext: {}
  modelSpec:
  - name: "bge-m3"
    repository: "lmcache/vllm-openai"
    tag: "2025-05-27-v1"
    modelURL: "BAAI/bge-m3"
    replicaCount: 1
    requestCPU: 6
    requestMemory: "30Gi"
    requestGPU: 1
    pvcStorage: "50Gi"
    vllmConfig:
      enablePrefixCaching: true
      maxModelLen: 32000
      v1: 1
    lmcacheConfig:
      enabled: true
      cpuOffloadingBufferSize: "60"
      enableController: true
      instanceId: "default1"
      controllerPort: "9000"
      workerPort: 8001
    env:
      - name: LMCACHE_LOG_LEVEL
        value: "DEBUG"
      - name: HF_TOKEN
        value: ""
  - name: "gemma3"
    repository: "lmcache/vllm-openai"
    tag: "2025-05-27-v1"
    modelURL: "google/gemma-3-27b-it"
    replicaCount: 1
    requestCPU: 6
    requestMemory: "70Gi"
    requestGPU: 1
    pvcStorage: "50Gi"
    vllmConfig:
      enablePrefixCaching: true
      maxModelLen: 32000
      v1: 1
    lmcacheConfig:
      enabled: true
      cpuOffloadingBufferSize: "60"
      enableController: true
      instanceId: "default2"
      controllerPort: "9000"
      workerPort: 8002
    env:
      - name: LMCACHE_LOG_LEVEL
        value: "DEBUG"
      - name: HF_TOKEN
        value: ""
        
routerSpec:
  repository: "lmcache/lmstack-router"
  tag: "latest"
  imagePullPolicy: "Always"
  enableRouter: true
  replicaCount: 1
  containerPort: 8000
  serviceType: ClusterIP
  servicePort: 80
  serviceDiscovery: "k8s"
  labels:
    environment: "router"
    release: "router"
  ingress:
    enabled: true
    className: "traefik"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-production"
      cert-manager.io/private-key-rotation-policy: Always
      cert-manager.io/private-key-algorithm: "ECDSA"
      cert-manager.io/private-key-size: "384"
      traefik.ingress.kubernetes.io/router.middlewares: "networking-limit-kdvz-ips@kubernetescrd"
    hosts:
      - host: vllm-router.example.tld
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: vllm-router.example.tld
        hosts:
          - vllm-router.example.tld
```

After some troubleshooting it seems to be a problem deployment-vllm-multi.yaml file. It looks like that the error is the double defined security context with the file on line 92-95 and and the variable based 194-196. 

Would it be possible to combine the two into one with defaults and variable?

### To Reproduce

Try to deploy the stack with argocd with any kind of deployment with helm via kustomize.
