### ISSUE TITLE
Download model from Object Storage

### ISSUE THREAD

**Issue by nitin302** [vllm-project/production-stack#69]
Need a solution to download a model from AWS storage, Azure Blob Storage or MinIO.

Creating this issue as requested here - https://github.com/vllm-project/production-stack/issues/67#issuecomment-2640572620

**Comment by ApostaC** [comment]
Thanks for helping us organize the feature requests! Will work on this soon!

**Comment by xqe2011** [comment]
Looking forward to this feature too. I am using RunAI Model Streamer to load models directly from s3 now.

**Comment by noa-neria** [comment]
Hi from the RunAI team,

Happy to confirm that you can load models directly from object storage in the production stack, by adding the necessary flags and credentials in your configuration file.

Using the following configuration file, we deployed vLLM with RunAI model streamer to read the model from object storage (S3, GCS, Minio and any S3 compatible storage)

```
servingEngineSpec:
  modelSpec:
  - name: "llama3"
    repository: "vllm/vllm-openai"
    tag: "v0.7.1"
    modelURL: "s3://core-llm/Llama-3-8b/"
    replicaCount: 1
    env:
    - name: AWS_ACCESS_KEY_ID
      value: "Your_key_here"
    - name: AWS_SECRET_ACCESS_KEY
      value: "Your_secret_here"
    - name: RUNAI_STREAMER_MEMORY_LIMIT
      value: "8388608000"
 
    pvcStorage: "5Gi"

    requestCPU: 1
    requestMemory: "30Gi"
    requestGPU: 1

    vllmConfig:
      extraArgs: ["--load-format", "runai_streamer"]
    hf_token: Your_token_here

```

`RUNAI_STREAMER_MEMORY_LIMIT`  is optional memory limit in bytes. If not specified, the RunAI streamer will allocate CPU memory in the total size of the model weights.

The RunAI streamer is an [open source project](https://github.com/run-ai/runai-model-streamer) integrated into vLLM.
The streamer provides fast streaming of model weights from Safetensors files (either in file system or object storage), saturating the storage bandwidth with parallel reads. Benchmarks can be found [here](https://www.run.ai/blog/run-ai-model-streamer-performance-benchmarks)
